import 'package:flutter/material.dart';
import '../models/app_models.dart';

class MockData {
  static List<ServiceCategory> categories = [
    const ServiceCategory(id: "electrician", name: "Electrician", icon: Icons.bolt_rounded, color: Color(0xFFF59E0B), workerCount: 42),
    const ServiceCategory(id: "plumber", name: "Plumber", icon: Icons.plumbing_rounded, color: Color(0xFF0284C7), workerCount: 38),
    const ServiceCategory(id: "carpenter", name: "Carpenter", icon: Icons.carpenter_rounded, color: Color(0xFFB45309), workerCount: 29),
    const ServiceCategory(id: "painter", name: "Painter", icon: Icons.format_paint_rounded, color: Color(0xFF8B5CF6), workerCount: 35),
    const ServiceCategory(id: "ac_technician", name: "AC Technician", icon: Icons.ac_unit_rounded, color: Color(0xFF06B6D4), workerCount: 24),
    const ServiceCategory(id: "cleaner", name: "Cleaner", icon: Icons.cleaning_services_rounded, color: Color(0xFF10B981), workerCount: 56),
    const ServiceCategory(id: "welder", name: "Welder", icon: Icons.hardware_rounded, color: Color(0xFF64748B), workerCount: 19),
    const ServiceCategory(id: "mason", name: "Mason", icon: Icons.foundation_rounded, color: Color(0xFFE11D48), workerCount: 22),
    const ServiceCategory(id: "driver", name: "Driver", icon: Icons.directions_car_rounded, color: Color(0xFF0D9488), workerCount: 31),
    const ServiceCategory(id: "gardener", name: "Gardener", icon: Icons.yard_rounded, color: Color(0xFF15803D), workerCount: 18),
  ];

  static List<WorkerProfile> sampleWorkers = [
    const WorkerProfile(
      id: "w-2",
      name: "Rohan Patel",
      trade: "Master Plumber",
      categoryId: "plumber",
      rating: 4.95,
      reviewsCount: 128,
      jobsCompleted: 142,
      experienceYears: 12,
      hourlyRate: 65.0,
      dailyRate: 480.0,
      location: "Central Heights",
      distanceKm: 2.3,
      isAvailableToday: true,
      verificationStatus: WorkerVerificationStatus.verified,
      skills: ["PEX Re-pipe", "Water Heaters", "Drain Snaking", "Gas Tightness", "Leak Detection", "Commercial Fixtures"],
      badges: ["Master Certified", "Top Rated 2026", "100% On-Time"],
      bio: "12+ years certified master plumbing veteran. Specializes in luxury residential remodels, leak detection, and multi-stage plumbing installations with zero mess.",
      avatarInitials: "RP",
      avatarColor: Color(0xFF0284C7),
      safetyScore: 98,
      portfolioTags: ["Emergency Repair", "Bathroom Remodel", "Pipe Relining"],
      reviews: [
        ReviewItem(
          authorName: "Sarah Jenkins",
          authorAvatar: "SJ",
          rating: 5.0,
          date: "3 days ago",
          comment: "Rohan fixed our kitchen mainline leak in under 45 minutes and clean-tested the entire line. Incredible speed and professionalism!",
          projectTitle: "Kitchen Drainage Overhaul",
        ),
        ReviewItem(
          authorName: "Michael Chen",
          authorAvatar: "MC",
          rating: 4.9,
          date: "1 week ago",
          comment: "Punctual, fully equipped with high-pressure testing tools, and very clear on the milestone costs.",
          projectTitle: "Master Bath Rough-in",
        ),
      ],
    ),
    const WorkerProfile(
      id: "w-3",
      name: "Darius Washington",
      trade: "Certified Electrician",
      categoryId: "electrician",
      rating: 4.88,
      reviewsCount: 94,
      jobsCompleted: 110,
      experienceYears: 9,
      hourlyRate: 70.0,
      dailyRate: 520.0,
      location: "Westside District",
      distanceKm: 3.8,
      isAvailableToday: true,
      verificationStatus: WorkerVerificationStatus.verified,
      skills: ["Panel Upgrades", "Smart Home Automation", "EV Chargers", "Conduit Bending", "Code Compliance", "Lighting Design"],
      badges: ["Licensed Journeyman", "Safety First Badge"],
      bio: "State-licensed electrical specialist with high-precision layout standards. Guaranteed passing municipal code inspections on first attempt.",
      avatarInitials: "DW",
      avatarColor: Color(0xFFD97706),
      safetyScore: 100,
      portfolioTags: ["200A Service", "Tesla Wall Connector", "Recessed LED"],
      reviews: [
        ReviewItem(
          authorName: "David Sterling",
          authorAvatar: "DS",
          rating: 5.0,
          date: "2 weeks ago",
          comment: "Upgraded our entire subpanel for new bathroom appliances. Flawless conduit work and passed inspection with no remarks.",
          projectTitle: "Subpanel Upgrade & GFCI Circuits",
        ),
      ],
    ),
    const WorkerProfile(
      id: "w-4",
      name: "Mateo Hernandez",
      trade: "Drywall & Plaster Specialist",
      categoryId: "mason",
      rating: 4.92,
      reviewsCount: 165,
      jobsCompleted: 215,
      experienceYears: 14,
      hourlyRate: 50.0,
      dailyRate: 380.0,
      location: "South Suburbs",
      distanceKm: 4.5,
      isAvailableToday: false,
      verificationStatus: WorkerVerificationStatus.verified,
      skills: ["Level 5 Finish", "Soundproofing", "Water Damage Repair", "Texture Matching", "Cornice Trim"],
      badges: ["Fast Worker", "Clean Site Guaranteed"],
      bio: "Equipped with dustless Festool sanders and automatic taping machines. Leaves your work site clean and ready for painters without delay.",
      avatarInitials: "MH",
      avatarColor: Color(0xFF059669),
      safetyScore: 95,
      portfolioTags: ["Acoustic Drywall", "Skim Coat", "Ceiling Repair"],
      reviews: [],
    ),
    const WorkerProfile(
      id: "w-5",
      name: "Elena Geller",
      trade: "Tiling & Stone Artisan",
      categoryId: "mason",
      rating: 4.97,
      reviewsCount: 88,
      jobsCompleted: 95,
      experienceYears: 8,
      hourlyRate: 75.0,
      dailyRate: 560.0,
      location: "Northridge",
      distanceKm: 1.9,
      isAvailableToday: true,
      verificationStatus: WorkerVerificationStatus.verified,
      skills: ["Porcelain Large Format", "Schluter Waterproofing", "Mosaics", "Heated Floors", "Mitered Edges"],
      badges: ["Master Artisan", "Flawless Alignment"],
      bio: "Specialist in bespoke tile patterns, zero-barrier curb-less walk-in showers, and watertight Schluter-Kerdi assemblies.",
      avatarInitials: "EG",
      avatarColor: Color(0xFF7C3AED),
      safetyScore: 99,
      portfolioTags: ["Herringbone Wall", "Schluter Shower", "Heated Marble"],
      reviews: [],
    ),
    const WorkerProfile(
      id: "w-6",
      name: "Samuel Brooks",
      trade: "Finish Carpenter",
      categoryId: "carpenter",
      rating: 4.82,
      reviewsCount: 64,
      jobsCompleted: 78,
      experienceYears: 11,
      hourlyRate: 60.0,
      dailyRate: 440.0,
      location: "East River",
      distanceKm: 5.2,
      isAvailableToday: true,
      verificationStatus: WorkerVerificationStatus.verified,
      skills: ["Custom Cabinetry", "Crown Molding", "Door Jamb Hanging", "Floating Vanities", "Built-ins"],
      badges: ["Precision Joinery"],
      bio: "Passionate about seamless joinery and exact trim alignment. Experienced in high-end bathroom & kitchen fixtures installation.",
      avatarInitials: "SB",
      avatarColor: Color(0xFF475569),
      safetyScore: 96,
      portfolioTags: ["Floating Vanity", "Wainscoting", "Solid Oak Doors"],
      reviews: [],
    ),
    const WorkerProfile(
      id: "w-7",
      name: "Carlos Rivera",
      trade: "HVAC & AC Master Technician",
      categoryId: "ac_technician",
      rating: 4.91,
      reviewsCount: 112,
      jobsCompleted: 130,
      experienceYears: 10,
      hourlyRate: 68.0,
      dailyRate: 500.0,
      location: "Downtown Core",
      distanceKm: 3.1,
      isAvailableToday: true,
      verificationStatus: WorkerVerificationStatus.verified,
      skills: ["Ductless Mini-Splits", "Refrigerant Recharging", "Air Balancing", "Thermostat Integration", "Emergency Heating"],
      badges: ["EPA Certified", "24/7 Available"],
      bio: "EPA Universal certified technician with specialized diagnostic gauges. Quick cooling and heating restoration with guaranteed workmanship warranty.",
      avatarInitials: "CR",
      avatarColor: Color(0xFF0EA5E9),
      safetyScore: 97,
      portfolioTags: ["Multi-Zone Split", "Compressor Swap", "Smart Nest Setup"],
      reviews: [],
    ),
    const WorkerProfile(
      id: "w-8",
      name: "Amina Al-Mansoor",
      trade: "Interior & Exterior Painting Lead",
      categoryId: "painter",
      rating: 4.89,
      reviewsCount: 79,
      jobsCompleted: 88,
      experienceYears: 7,
      hourlyRate: 48.0,
      dailyRate: 360.0,
      location: "Greenwood Valley",
      distanceKm: 6.4,
      isAvailableToday: true,
      verificationStatus: WorkerVerificationStatus.verified,
      skills: ["Airless Spraying", "Color Matching", "Cabinet Enameling", "Exterior Weather-Seal", "Epoxy Floors"],
      badges: ["Crisp Edges Guarantee", "Eco-Paint Specialist"],
      bio: "Professional painter utilizing zero-VOC premium paints and precision masking techniques. Flawless coverage and sharp ceiling trim lines.",
      avatarInitials: "AA",
      avatarColor: Color(0xFF9333EA),
      safetyScore: 99,
      portfolioTags: ["Cabinet Respray", "Accent Walls", "Weatherproof Exterior"],
      reviews: [],
    ),
  ];

  static List<CustomerBooking> sampleBookings = [
    CustomerBooking(
      bookingId: "BK-9041",
      worker: sampleWorkers[0], // Rohan Patel
      serviceTitle: "Rough Plumbing & Drainage Lines",
      categoryName: "Plumbing",
      bookingDate: "Tomorrow, Oct 19",
      timeSlot: "09:00 AM - 01:00 PM (4 hrs)",
      address: "742 Evergreen Terrace, Metro West District",
      jobDescription: "Reroute hot/cold PEX water supply lines and connect 4-inch PVC waste stack for new double vanity & shower.",
      estimatedHours: 4.0,
      laborCost: 260.0,
      serviceFee: 25.0,
      totalAmount: 285.0,
      status: JobStatus.booked,
      specialInstructions: "Main shutoff valve is located in the basement adjacent to water meter. Gate code is #4921.",
    ),
    CustomerBooking(
      bookingId: "BK-8820",
      worker: sampleWorkers[1], // Darius Washington
      serviceTitle: "200A Subpanel & GFCI Circuits",
      categoryName: "Electrician",
      bookingDate: "Oct 22, 2026",
      timeSlot: "02:00 PM - 05:00 PM (3 hrs)",
      address: "742 Evergreen Terrace, Metro West District",
      jobDescription: "Install 20A dedicated circuits for steam shower and heated floors.",
      estimatedHours: 3.0,
      laborCost: 210.0,
      serviceFee: 20.0,
      totalAmount: 230.0,
      status: JobStatus.readyToBook,
      specialInstructions: "Breaker panel is in the garage.",
    ),
    CustomerBooking(
      bookingId: "BK-7612",
      worker: sampleWorkers[3], // Elena Geller
      serviceTitle: "Tile Backsplash & Herringbone Installation",
      categoryName: "Mason",
      bookingDate: "Sep 28, 2026",
      timeSlot: "08:30 AM - 04:30 PM (8 hrs)",
      address: "742 Evergreen Terrace, Metro West District",
      jobDescription: "Waterproof membrane and subway porcelain tile installation.",
      estimatedHours: 8.0,
      laborCost: 600.0,
      serviceFee: 45.0,
      totalAmount: 645.0,
      status: JobStatus.completed,
      specialInstructions: "Completed and signed off with 5-star review.",
    ),
  ];

  static List<NotificationItem> sampleNotifications = [
    const NotificationItem(
      id: "notif-1",
      title: "Worker On The Way",
      message: "Rohan Patel (Plumber) has departed and will arrive at 742 Evergreen Terrace in ~18 minutes.",
      timeAgo: "10m ago",
      icon: Icons.directions_car_rounded,
      color: Color(0xFF0284C7),
      isRead: false,
    ),
    const NotificationItem(
      id: "notif-2",
      title: "Milestone Prerequisite Cleared",
      message: "Demolition Step 1 completed. Step 2 (Rough Plumbing) is now ready for on-site work.",
      timeAgo: "2h ago",
      icon: Icons.check_circle_rounded,
      color: Color(0xFF10B981),
      isRead: false,
    ),
    const NotificationItem(
      id: "notif-3",
      title: "Booking Confirmed: Darius Washington",
      message: "Electrician booking confirmed for Oct 22. Escrow deposit of \$230.00 is secured in wallet.",
      timeAgo: "1d ago",
      icon: Icons.event_available_rounded,
      color: Color(0xFF8B5CF6),
      isRead: true,
    ),
    const NotificationItem(
      id: "notif-4",
      title: "Review Request: Elena Geller",
      message: "How did Elena do on your Tile Backsplash job? Leave feedback to help other homeowners.",
      timeAgo: "3d ago",
      icon: Icons.star_rounded,
      color: Color(0xFFF59E0B),
      isRead: true,
    ),
  ];

  static List<JobStep> sampleJobSteps = [
    const JobStep(
      id: "step-1",
      title: "Site Demolition & Debris Clearing",
      tradeCategory: "Demolition & Masonry",
      sequenceOrder: 1,
      dependsOnStepIds: [],
      status: JobStatus.completed,
      estimatedDuration: "2 Days",
      estimatedCost: 650.0,
      assignedWorkerId: "w-1",
      assignedWorkerName: "Marcus Vance",
      assignedWorkerTrade: "Demolition Lead",
      assignedWorkerAvatar: "MV",
      scheduledDate: "Oct 12 - Oct 14",
      description: "Tear down non-load-bearing partition walls, strip flooring, and load rubble into waste dumpster.",
      checklist: ["Isolate electrical subpanel", "Erect plastic dust barriers", "Clear drywall & framing", "Haul rubble to dumpster"],
      completionProofUrls: ["photo1", "photo2"],
    ),
    const JobStep(
      id: "step-2",
      title: "Rough Plumbing & Drainage Lines",
      tradeCategory: "Plumbing",
      sequenceOrder: 2,
      dependsOnStepIds: ["step-1"],
      status: JobStatus.inProgress,
      estimatedDuration: "3 Days",
      estimatedCost: 1200.0,
      assignedWorkerId: "w-2",
      assignedWorkerName: "Rohan Patel",
      assignedWorkerTrade: "Master Plumber",
      assignedWorkerAvatar: "RP",
      scheduledDate: "Oct 15 - Oct 18",
      description: "Reroute hot/cold PEX water supply lines and connect 4-inch PVC waste stack for new double vanity & shower.",
      checklist: ["Shut off main water valve", "Trench shower drain line", "Install PEX manifold lines", "Pressure test water lines to 60 PSI"],
      completionProofUrls: ["photo3"],
    ),
    const JobStep(
      id: "step-3",
      title: "Electrical Rough-in & Conduit Run",
      tradeCategory: "Electrical",
      sequenceOrder: 3,
      dependsOnStepIds: ["step-1"],
      status: JobStatus.readyToBook,
      estimatedDuration: "2 Days",
      estimatedCost: 950.0,
      assignedWorkerId: null,
      assignedWorkerName: null,
      assignedWorkerTrade: null,
      assignedWorkerAvatar: null,
      scheduledDate: "Oct 19 - Oct 21",
      description: "Install 20A GFCI dedicated circuits, recessed lighting wiring, and exhaust fan ducting ready for inspection.",
      checklist: ["Run 12/2 Romex cables", "Mount junction boxes", "Test grounding bus", "Label breaker schedules"],
    ),
    const JobStep(
      id: "step-4",
      title: "Drywall Hanging, Mudding & Taping",
      tradeCategory: "Drywall & Plaster",
      sequenceOrder: 4,
      dependsOnStepIds: ["step-2", "step-3"],
      status: JobStatus.pendingPredecessor,
      estimatedDuration: "3 Days",
      estimatedCost: 800.0,
      assignedWorkerId: null,
      assignedWorkerName: null,
      assignedWorkerTrade: null,
      assignedWorkerAvatar: null,
      scheduledDate: "Oct 22 - Oct 25",
      description: "Hang 5/8\" moisture-resistant drywall sheets, apply 3 coats of joint compound, and feather sand smooth.",
      checklist: ["Insulation check prior to board seal", "Screw spacing 12\" on center", "Corner bead taping", "Level 4 finish sanding"],
    ),
    const JobStep(
      id: "step-5",
      title: "Custom Tiling & Waterproof Membrane",
      tradeCategory: "Tiling & Flooring",
      sequenceOrder: 5,
      dependsOnStepIds: ["step-4"],
      status: JobStatus.pendingPredecessor,
      estimatedDuration: "4 Days",
      estimatedCost: 1650.0,
      assignedWorkerId: null,
      assignedWorkerName: null,
      assignedWorkerTrade: null,
      assignedWorkerAvatar: null,
      scheduledDate: "Oct 26 - Oct 30",
      description: "Apply waterproof tanking coat, lay herringbone porcelain floor tiles, and subway tile shower walls.",
      checklist: ["Hydro-barrier leak test", "Laser-level layout alignment", "Epoxy grout application", "Perimeter silicone sealant"],
    ),
    const JobStep(
      id: "step-6",
      title: "Cabinetry, Fixtures & Final Trim",
      tradeCategory: "Carpentry & Finishing",
      sequenceOrder: 6,
      dependsOnStepIds: ["step-5"],
      status: JobStatus.pendingPredecessor,
      estimatedDuration: "2 Days",
      estimatedCost: 900.0,
      assignedWorkerId: null,
      assignedWorkerName: null,
      assignedWorkerTrade: null,
      assignedWorkerAvatar: null,
      scheduledDate: "Nov 01 - Nov 03",
      description: "Mount floating vanity, install matte black faucets, fit mirror with backlit LED, and install baseboards.",
      checklist: ["Vanity wall stud anchoring", "Faucet cartridge leak inspection", "Door soft-close alignment", "Final punch list signoff"],
    ),
  ];

  static List<Project> sampleProjects = [
    Project(
      id: "proj-101",
      title: "Complete Master Bathroom Remodel",
      clientName: "David Sterling",
      clientPhone: "+1 (555) 234-8901",
      locationAddress: "742 Evergreen Terrace",
      city: "Metro West District",
      totalBudget: 6150.0,
      amountPaid: 1850.0,
      startDate: "Oct 12, 2026",
      expectedCompletionDate: "Nov 03, 2026",
      progressPercent: 0.35,
      steps: sampleJobSteps,
    ),
    const Project(
      id: "proj-102",
      title: "Commercial Kitchen Upgrade & Gas Line",
      clientName: "Elena Rostova",
      clientPhone: "+1 (555) 876-5432",
      locationAddress: "128 Commerce Blvd, Suite 4B",
      city: "Downtown Hub",
      totalBudget: 14200.0,
      amountPaid: 4500.0,
      startDate: "Nov 01, 2026",
      expectedCompletionDate: "Nov 28, 2026",
      progressPercent: 0.15,
      steps: [],
    ),
  ];

  static List<DisputeTicket> sampleDisputes = [
    const DisputeTicket(
      id: "DISP-892",
      projectId: "proj-101",
      projectTitle: "Master Bathroom Remodel",
      stepTitle: "Rough Plumbing Inspection Delay",
      raisedByName: "David Sterling (Customer)",
      workerName: "Rohan Patel",
      dateRaised: "Oct 16, 2026",
      reason: "Permit inspector requested slight slope adjustment on 3-inch shower vent before dry-in.",
      status: "In Mediation",
      disputedAmount: 400.0,
    ),
  ];

  static List<TimeSlot> sampleSchedule = [
    const TimeSlot(id: 'ts-1', startTime: '09:00 AM', endTime: '11:00 AM', status: SlotStatus.booked, title: 'Electrical Repair', subtitle: '742 Evergreen Terrace'),
    const TimeSlot(id: 'ts-2', startTime: '11:30 AM', endTime: '01:00 PM', status: SlotStatus.booked, title: 'Plumbing', subtitle: '128 Commerce Blvd'),
    const TimeSlot(id: 'ts-3', startTime: '01:00 PM', endTime: '02:00 PM', status: SlotStatus.breakTime, title: 'Lunch Break'),
    const TimeSlot(id: 'ts-4', startTime: '02:00 PM', endTime: '05:00 PM', status: SlotStatus.booked, title: 'AC Installation', subtitle: '990 Spring St'),
    const TimeSlot(id: 'ts-5', startTime: '05:00 PM', endTime: '06:00 PM', status: SlotStatus.available),
  ];

  static List<JobRequest> sampleJobRequests = [
    const JobRequest(id: 'jr-1', customerName: 'Sarah Jenkins', serviceTitle: 'Ceiling Fan Installation', date: 'Tomorrow', time: '09:00 AM', location: '12 Maple Street', estimatedEarnings: 120.0, distanceKm: 3.2),
    const JobRequest(id: 'jr-2', customerName: 'Michael Chang', serviceTitle: 'Leaky Pipe Repair', date: 'Oct 24, 2026', time: '02:30 PM', location: '88 Oak Avenue', estimatedEarnings: 85.0, distanceKm: 5.1),
    const JobRequest(id: 'jr-3', customerName: 'Elena Rostova', serviceTitle: 'Gas Line Inspection', date: 'Oct 25, 2026', time: '10:00 AM', location: '128 Commerce Blvd', estimatedEarnings: 200.0, distanceKm: 7.8),
  ];
}

